# .github/workflows/deploy.yml
name: Deploy React App

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install & build
        run: |
          npm ci
          npm run build

      - name: Deploy via LFTP (SFTP)
        uses: pressidium/lftp-mirror-action@v1
        with:
          host: ${{ secrets.SFTP_HOST }}
          port: 22
          user: ${{ secrets.SFTP_USER }}
          pass: ${{ secrets.SFTP_PASS }}
          local_dir: './dist'                 # or 'build' if that’s your output
          remote_dir: '/main/'                     # deploy to web root
          exclude: |
            **/workspace/**                     # keep your /workspace intact
