# .github/workflows/deploy.yml
name: Deploy React App

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install & build
        run: |
          npm ci
          npm run build

      - name: Deploy via LFTP (SFTP)
        uses: pressidium/lftp-mirror-action@v1
        with:
          host: ${{ secrets.SFTP_HOST }}
          port: 22
          user: ${{ secrets.SFTP_USER }}
          pass: ${{ secrets.SFTP_PASS }}
          onlyNewer: true
          settings: 'sftp:auto-confirm=yes'
          localDir: 'dist/'
          remoteDir: '/main'
          reverse: true
          ignoreFile: '.lftpignore'
